---
- name: F5 Command
  gather_facts: false
  hosts: bigip
  vars: 
    username: admin 
    password: 1qaz2wsX

  tasks:
  - name: show sys version 
    bigip_command:
       commands: show sys version 
       server: "{{ inventory_hostname }}"
       user: "{{ username }}"
       password: "{{ password }}"
       validate_certs: False
    delegate_to: localhost
    register: result 

  - debug: 
       var: result 


