---
- name: F5 Opp
  gather_facts: false
  hosts: all
  vars: 
    ntp_servers:
            - '0.centos.pool.ntp.org'
            - '1.centos.pool.ntp.org'  
            - '2.centos.pool.ntp.org' 
    banner_text: "------ Welcome to BIGIP Red Hat Ansible ! -------"       

  tasks:
  - name: Configure NTP server on BIG-IP
    bigip_device_ntp:
       server: "{{ inventory_hostname }}"
       user: "{{ username }}"
       password: "{{ password }}"
       ntp_servers: "{{ ntp_servers }}"
       validate_certs: False
    delegate_to: localhost

  - name: Manage SSHD setting on BIG-IP
    bigip_device_sshd:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      banner: "enabled"
      banner_text: " {{ banner_text }}"
      validate_certs: False
    delegate_to: localhost

  - name: Set the DNS setting on the BIG-IP
    bigip_device_dns:
      name_servers:
        - 8.8.8.8
      search:
        - localdomain
      state: present
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
    delegate_to: localhost

