---
- name: F5 Opp
  gather_facts: false
  hosts: all
  tasks:

  - name: Collect BIG-IP facts
    bigip_facts:
        server: "{{ inventory_hostname }}"
        user: "{{ F5_USER }}"
        password: "{{ F5_PASSWORD }}"
        include: "interface,vlan"
        validate_certs: "no"
    delegate_to: localhost
